exec-once = [workspace 1 silent] ghostty -e tmux
exec-once = [workspace 1 silent] firefox
exec-once = [workspace 2 silent] steam
exec-once = [workspace 3 silent] Telegram
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- nm-applet --indicator
