# Floating windows
windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 800 600, match:tag floating-window

windowrule = tag +floating-window, match:class (blueberry.py|Impala|Wiremix|org.gnome.NautilusPreviewer)
windowrule = tag +floating-window, match:class (xdg-desktop-portal-gtk|org.gnome.Nautilus), match:title ^(Open.*Files?|Open Folder|Save.*Files?|Save.*As|Save|All Files)

# Fullscreen screensaver
windowrule = fullscreen on, match:class Screensaver

# No transparency on media windows
windowrule = opacity 1 1, match:class ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$

# Popped window rounding
windowrule = rounding 8, match:tag pop
